In [14]:
# 多维数组的切片处理
import numpy as np
import torch

x = torch.rand(1, 2, 3)

x_last = x[..., 0]       # 等价于 x[:,:,:,0]，选择最后一维的第0个元素
x_first = x[0, ...]       # 等价于 x[0,:,:,:]，选择第0个维度的所有元素
x_more = x[..., None]    # 等价于 x[:,:,:,:,None]，在最后添加一个维度
print(x_more.shape)
print(x)

torch.Size([1, 2, 3, 1])
tensor([[[0.6401, 0.9784, 0.1812],
         [0.0556, 0.7807, 0.1215]]])


In [20]:
x = torch.tensor([1,2,3])
print(x)
print(x.shape)

x_repeat = x.repeat(1,2) # 沿第0轴重复2次，1轴重复2次
print(x_repeat)
x_repeat.shape

tensor([1, 2, 3])
torch.Size([3])
tensor([[1, 2, 3, 1, 2, 3]])


torch.Size([1, 6])